language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'
  - mysql -e 'SHOW DATABASES;'
script: mvn clean verify
after_success:
  - mvn clean test jacoco:report coveralls:report
