language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - sudo apt-get install libmysql-java
  - export CLASSPATH=$CLASSPATH:/usr/share/java/mysql-connector-java.jar
  - mysql -e 'CREATE DATABASE SERVER;'
  - mysql -e 'use SERVER';
  - mysql -e 'use SERVER; CREATE TABLE STUDENT (STUDENT_NO varchar(10) NOT NULL,STUDENT_NAME varchar(100) DEFAULT NULL,STUDENT_EMAIL varchar(100) DEFAULT NULL,STUDENT_DATABASE varchar(30) DEFAULT NULL,PRIMARY KEY (STUDENT_NO),UNIQUE KEY STUDENT_DATABASE (STUDENT_DATABASE));'
  - mysql -e 'INSERT INTO SERVER.STUDENT VALUES ("1606558","Carl Ginster","carl.ginster1@students.wits.ac.za","d1606558");'
  - mysql -e 'SELECT * FROM SERVER.STUDENT;'
  - mysql -e 'DESC SERVER.STUDENT;'
  - mysql -e 'SHOW DATABASES;'
  - mysql -e 'use SERVER; CREATE TABLE SAVED_QUERY (STUDENT_NO varchar(10) DEFAULT NULL, SAVED_QUERY_NAME varchar(100) DEFAULT NULL, SAVED_QUERY_ID int(11) NOT NULL AUTO_INCREMENT, SAVED_QUERY varchar(20000) DEFAULT NULL,  PRIMARY KEY (SAVED_QUERY_ID),  KEY STUDENT_NO (STUDENT_NO),  CONSTRAINT SAVED_QUERY_ibfk_1 FOREIGN KEY (STUDENT_NO) REFERENCES STUDENT (STUDENT_NO));'
  - mysql -e 'DESC SERVER.SAVED_QUERY'
  - mysql -e 'use SERVER; CREATE TABLE STUDENT_HISTORY (HISTORY_QUERY varchar(20000) DEFAULT NULL, HISTORY_DATE varchar(35) DEFAULT NULL, HISTORY_TIME time DEFAULT NULL,  HISTORY_ID int(7) NOT NULL AUTO_INCREMENT, STUDENT_NO varchar(10) DEFAULT NULL, PRIMARY KEY (HISTORY_ID), KEY STUDENT_NO (STUDENT_NO),  CONSTRAINT STUDENT_HISTORY_ibfk_1 FOREIGN KEY (STUDENT_NO) REFERENCES STUDENT (STUDENT_NO));'
  - mysql -e 'INSERT INTO SERVER.STUDENT_HISTORY  (HISTORY_QUERY,HISTORY_DATE,HISTORY_TIME,STUDENT_NO) VALUES ("SELECT * FROM STUDENT_HISTORY","2019-04-23','11:14:58","1606558"),("SELECT * FROM STUDENT_HISTORY", "2019-04-23","11:14:58","1606558");'
script: mvn clean verify
after_success:
  - mvn clean test jacoco:report coveralls:report
