language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE SERVER;'
  - mysql -e 'use SERVER';
  - mysql -e 'use SERVER; CREATE TABLE STUDENT (STUDENT_NO varchar(10) NOT NULL,STUDENT_NAME varchar(100) DEFAULT NULL,STUDENT_EMAIL varchar(100) DEFAULT NULL,STUDENT_DATABASE varchar(30) DEFAULT NULL,PRIMARY KEY (STUDENT_NO),UNIQUE KEY STUDENT_DATABASE (STUDENT_DATABASE));'
  - mysql -e 'DESC SERVER.STUDENT;'
  - mysql -e 'SHOW DATABASES;'
  - mysql -e 'use SERVER; CREATE TABLE SAVED_QUERY (STUDENT_NO varchar(10) DEFAULT NULL, SAVED_QUERY_NAME varchar(100) DEFAULT NULL, SAVED_QUERY_ID int(11) NOT NULL AUTO_INCREMENT, SAVED_QUERY varchar(20000) DEFAULT NULL,  PRIMARY KEY (SAVED_QUERY_ID),  KEY STUDENT_NO (STUDENT_NO),  CONSTRAINT SAVED_QUERY_ibfk_1 FOREIGN KEY (STUDENT_NO) REFERENCES STUDENT (STUDENT_NO));'
  - mysql -e 'DESC SERVER.SAVED_QUERY'
script: mvn clean verify
after_success:
  - mvn clean test jacoco:report coveralls:report
