language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE SERVER;'
  - mysql -e 'use SERVER';
  - mysql -e 'use SERVER; CREATE TABLE STUDENT (STUDENT_NO varchar(10) NOT NULL,STUDENT_NAME varchar(100) DEFAULT NULL,STUDENT_EMAIL varchar(100) DEFAULT NULL,STUDENT_DATABASE varchar(30) DEFAULT NULL,PRIMARY KEY (STUDENT_NO),UNIQUE KEY STUDENT_DATABASE (STUDENT_DATABASE));'
  - mysql -e 'DESC SERVER.STUDENT;'
  - mysql -e 'SHOW DATABASES;'
script: mvn clean verify
after_success:
  - mvn clean test jacoco:report coveralls:report
